helm:
  global:
    options:
      syncPolicy: Automatic

      useCSV: "False"
      installPlanApproval: Automatic

  applications:
  - name: acm
    namespace: default
    project: datacenter
    path: applications/acm

