global:
  options:
    useCSV: True
    syncPolicy: Automatic
    installPlanApproval: Automatic

site:
  name: hub

  proposedOptions:
    manageGitops: True
    isHubCluster: True

  namespaces:
  - open-cluster-management

  subscriptions:
  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.3
    csv: advanced-cluster-management.v2.3.2

  projects:
  - hub

  applications:
  - name: acm
    namespace: open-cluster-management
    project: hub
    path: applications/acm

  - name: vault
    namespace: vault
    project: hub
    chart: https://github.com/hashicorp/vault-helm

  managedSites:
  - name: region-one
    helmOverrides:
    - name: site.isHubCluster
      value: false
    clusterSelector:
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift

  - name: region-two
    helmOverrides:
    - name: site.isHubCluster
      value: false
    clusterSelector:
      matchExpressions:
      - key: vendor
        operator: In
        values:
          - OpenShift
#
#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main

#  managedSites:
#  - name: factory
#    # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#    targetRevision: main
#    path: applications/factory
#    helmOverrides:
#    - name: site.isHubCluster
#      value: false
#    clusterSelector:
#      matchExpressions:
#      - key: vendor
#        operator: In
#        values:
#          - OpenShift
