global:
  # Needed by vault to avoid trying to set some security contexts which do not apply on openshift
  # See https://github.com/hashicorp/vault-helm/issues/343 for more infos
  openshift: true

# This value can be changed to "true" to deploy the server in dev mode.  However, when this is done, the vault
# server will not store any data and this should NEVER be done in production.
#server:
#  dev:
#    enabled: false
#
#  # Values from values.openshift.yaml in common/vault to work better with openshift
#  image:
#    repository: "registry.connect.redhat.com/hashicorp/vault"
#    tag: "1.9.0-ubi"
#
## Values from values.openshift.yaml in common/vault to work better with openshift
#injector:
#  image:
#    repository: "registry.connect.redhat.com/hashicorp/vault-k8s"
#    tag: "0.14.1-ubi"
#
#  agentImage:
#    repository: "registry.connect.redhat.com/hashicorp/vault"
#    tag: "1.9.0-ubi"

clusterGroup:
  name: hub

  proposedOptions:
    manageGitops: True
    isHubCluster: True

  namespaces:
  - open-cluster-management
  - vault

  subscriptions:
  - name: advanced-cluster-management
    namespace: open-cluster-management
    channel: release-2.3
    csv: advanced-cluster-management.v2.3.5

  projects:
  - hub

  applications:
  - name: acm
    namespace: open-cluster-management
    project: hub
    path: common/acm
    ignoreDifferences:
    - group: internal.open-cluster-management.io
      kind: ManagedClusterInfo
      jsonPointers:
        - /spec/loggingCA

  - name: vault
    namespace: vault
    project: hub
    path: common/vault
    overrides:
    - name: server.dev.enabled
      value: no
      forceString: "True"
    - name: global.openshift
      value: yes
      forceString: "True"
    - name: server.image.repository
      value: "registry.connect.redhat.com/hashicorp/vault"
    - name: server.image.tag
      value: "1.9.0-ubi"
    - name: injector.image.repository
      value: "registry.connect.redhat.com/hashicorp/vault-k8s"
    - name: injector.image.tag
      value: "0.14.1-ubi"
    - name: injector.agentImage.repository
      value: "registry.connect.redhat.com/hashicorp/vault"
    - name: injector.agentImage.tag
      value: "1.9.0-ubi"

  managedClusterGroups:
  - name: region-one
    helmOverrides:
    - name: clusterGroup.isHubCluster
      value: false
    clusterSelector:
      matchLabels:
        clusterGroup: region-one

#  To have apps in multiple flavors, use namespaces and use helm overrides as appropriate
#
#  - name: pipelines
#    namespace: production
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: stable
#    overrides:
#    - name: myparam
#      value: myparam
#
#  - name: pipelines
#    namespace: staging
#    project: datacenter
#    path: applications/pipeline
#    repoURL: https://github.com/you/applications.git
#    targetRevision: main
#
#   Additional applications
#   Be sure to include additional resources your apps will require
#   +X machines
#   +Y RAM
#   +Z CPU
#  - name: vendor-app
#    namespace: default
#    project: vendor
#    path: path/to/myapp
#    repoURL: https://github.com/vendor/applications.git
#    targetRevision: main

#  managedSites:
#  - name: factory
#    # repoURL: https://github.com/dagger-refuse-cool/manuela-factory.git
#    targetRevision: main
#    path: applications/factory
#    helmOverrides:
#    - name: site.isHubCluster
#      value: false
#    clusterSelector:
#      matchExpressions:
#      - key: vendor
#        operator: In
#        values:
#          - OpenShift
