apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: config-demo
spec:
  lookupPolicy:
    local: true
  tags:
  - name: apache
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/httpd-24
    importPolicy: {}
    referencePolicy:
      type: Local
