kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vault
  namespace: vault
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/name: vault
    argocd.argoproj.io/instance: vault
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: vault.{{ .Values.global.clusterHubDomain }}
  to:
    kind: Service
    name: vault
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
status:
