{{- $valuesURL :=  cat .Values.main.git.repoURL "/raw/" .Values.main.git.revision "/values-blueprint.yaml" -}}
{{- $valuesURLFixed :=  $valuesURL | replace " " "" | replace ".git" "" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  project: default
  source:
    repoURL: {{ .Values.main.git.repoURL }}
    targetRevision: {{ .Values.main.git.revision }}
    path: applications/bootstrap
    helm:
      valueFiles:
      - {{ coalesce .Values.main.git.valuesURL $valuesURLFixed }}
      #- ../../values-blueprint.yaml
      parameters:
        - name: global.repoURL
          value: $ARGOCD_APP_SOURCE_REPO_URL
        - name: global.targetRevision
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        - name: global.valuesURL
          value: {{ coalesce .Values.main.git.valuesURL $valuesURLFixed }}
{{- if eq .Values.main.options.syncPolicy "Automatic" }}
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
{{- end }}
