apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  project: default
  source:
    repoURL: {{ .Values.main.git.repoURL }}
    targetRevision: {{ .Values.main.git.revision }}
    path: applications/bootstrap
{{- if eq .Values.main.options.syncPolicy "Automatic" }}
  syncPolicy:
    automated: 
      prune: false
      selfHeal: false
{{- end }}
