main:
  git:
    repoURL: git@github.com:hybrid-cloud-patterns/gitops.git
    revision: main
    #valuesDirectoryURL: https://github.com/hybrid-cloud-patterns/industrial-edge/raw/main/

  options:
    syncPolicy: Automatic
    installPlanApproval: Automatic
    useCSV: False
    bootstrap: True

  gitops:
    channel: stable
    source: redhat-operators
    csv: v1.2.0

  siteName: example

global:
  imageregistry:
    type: quay

secrets:
  # NEVER COMMIT THESE VALUES TO GIT
  enabled: false
  imageregistry:
    # Quay -> Robot Accounts -> Robot Login
    account: STRING
    token:   STRING

  git:
    # Go to: https://github.com/settings/tokens
    username: STRING
    token: STRING

  aws:
    s3Secret: BASE64STRING 