- name: MultiCloud-GitOps bootstrap
  hosts: localhost
  connection: local
  tasks:
  - name: Make sure make is installed
    become: true
    ansible.builtin.package:
      name: make
      state: present

  - name: Launch the installation
    ansible.builtin.command: "make install"
