- name: MultiCloud-GitOps bootstrap
  hosts: localhost
  connection: local
  tasks:
  - name: Make sure make is installed
    become: true
    ansible.builtin.package:
      name: make
      state: present

  - name: Launch the installation
    ansible.builtin.command: make install
    args:
      chdir: "{{ lookup('env', 'PWD') }}"
    register: output

  - name: Print output of installation
    ansible.builtin.debug:
      msg: "{{ output }}"
