{{- range .Values.site.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Release.Name }}-{{ $.Values.site.name }}-{{ .name }}
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: {{ default "openshift-gitops" .namespace }}
  project: {{ .project }}
  source:
    repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
    targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }}
    path: {{ .path }}
    {{- if .plugin }}
    plugin: {{ .plugin | toPrettyJson }}
    {{- else if not .kustomize }}
    helm:
      valueFiles:
      - "{{ coalesce .valuesDirectoryURL $.Values.global.valuesDirectoryURL }}/values-global.yaml"
      - "{{ coalesce .valuesDirectoryURL $.Values.global.valuesDirectoryURL }}/values-{{ $.Values.site.name }}.yaml"
      # Watch the progress of https://issues.redhat.com/browse/GITOPS-891 and update accordingly
      parameters:
        - name: global.repoURL
          value: $ARGOCD_APP_SOURCE_REPO_URL
        - name: global.targetRevision
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        - name: global.valuesDirectoryURL
          value: {{ coalesce .valuesDirectoryURL $.Values.global.valuesDirectoryURL }}
        {{- range .overrides }}
        - name: {{ .name }}
          value: {{ .value }}
        {{- end }}
    {{- end }}
  ignoreDifferences:
  - group: internal.open-cluster-management.io
    kind: ManagedClusterInfo
    jsonPointers:
    - /spec/loggingCA
{{- if eq $.Values.global.options.syncPolicy "Automatic" }}
  syncPolicy:
    automated: {}
    #  selfHeal: true
{{- end }}
---
{{- end }}
