{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: {{ default "openshift-gitops" .namespace }}
  project: {{ .project }}
  source:
    repoURL: {{ coalesce .repoURL $.Values.global.repoURL }}
    targetRevision: {{ coalesce .targetRevision $.Values.global.targetRevision }}
    path: {{ .path }}
    helm:
      valueFiles:
      - {{ .Values.global.valuesURL }}
      parameters:
        - name: global.repoURL
          value: $ARGOCD_APP_SOURCE_REPO_URL
        - name: global.targetRevision
          value: $ARGOCD_APP_SOURCE_TARGET_REVISION
        - name: global.valuesURL
          value: {{ $.Values.global.valuesURL }}
{{- if eq $.Values.global.options.syncPolicy "Automatic" }}
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
{{- end }}
---
{{- end }}
