{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: {{ default "openshift-gitops" .namespace }}
  project: {{ .project }}
  source:
    repoURL: $ARGOCD_APP_SOURCE_REPO_URL
    targetRevision: $ARGOCD_APP_SOURCE_TARGET_REVISION
    path: {{ .path }}
    helm:
      valueFiles:
      - ../../values-blueprint.yaml
{{- if eq $.Values.global.options.syncPolicy "Automatic" }}
  syncPolicy:
    automated: 
      prune: false
      selfHeal: false
{{- end }}
---
{{- end }}
