{{- range .Values.site.namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: {{ default "blueprint" $.Release.name }}
    argocd.argoproj.io/managed-by: {{ $.Values.site.name }}-gitops
  name: {{ . }}
spec:
---
{{- end }}
