{{- range .Values.site.namespaces }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ . }}-operator-group
  namespace: {{ . }}
spec:
  targetNamespaces:
  - {{ . }}
---
{{- end }}