{{- range .Values.applications }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  name: {{ .name }}
  source: {{ .source }}
  sourceNamespace: openshift-marketplace
  channel: {{ .channel }}
  installPlanApproval: {{ .Values.global.options.installPlanApproval }}
  {{- if .Values.global.options.useCSV }}
  startingCSV: {{ .name }}.{{ .csv }}
  {{- end }}  
---
{{- end }}
