{{- range .Values.site.subscriptions }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ default "openshift-operators" .namespace }}
spec:
  name: {{ .name }}
  source: {{ .source }}
  sourceNamespace: {{ default "openshift-marketplace" .sourceNamespace }}
  channel: {{ .channel }}
  installPlanApproval: {{ coalesce .installPlanApproval $.Values.global.options.installPlanApproval }}
  {{- if $.Values.global.options.useCSV }}
  startingCSV: {{ .name }}.{{ .csv }}
  {{- end }}  
---
{{- end }}
